"""Research agent domain models and proposal schemas (M7-1, Issue 217).

Provides immutable domain models for research context packets, hypothesis
proposals, experiment specification proposals, proposal validation reports,
canonical content hashing, and untrusted agent boundary enforcement.
"""

from collections.abc import Mapping
from decimal import Decimal
from enum import StrEnum
from typing import Any, Literal, Self
from uuid import UUID

from pydantic import model_validator

from drift.domain.common import (
    UUID7,
    FrozenModel,
    ImmutableJSON,
    NonBlankStr,
    SHA256Hash,
    UTCDateTime,
    _freeze_json,
)
from drift.serialization.canonical import content_hash

RESEARCH_AGENT_SCHEMA_VERSION: Literal["1"] = "1"


class ResearchAgentRole(StrEnum):
    """The persona and research objective of an autonomous research agent."""

    ALPHA_RESEARCHER = "alpha_researcher"
    RISK_CRITIC = "risk_critic"
    PORTFOLIO_CONSTRUCTOR = "portfolio_constructor"


class ProposalValidationStatus(StrEnum):
    """Deterministic validation result for an agent proposal."""

    ACCEPTED = "accepted"
    REJECTED_DUPLICATE_PARAMETERS = "rejected_duplicate_parameters"
    REJECTED_FORBIDDEN_VARIATION = "rejected_forbidden_variation"
    REJECTED_OUT_OF_BOUNDS = "rejected_out_of_bounds"
    REJECTED_CIRCULAR_LINEAGE = "rejected_circular_lineage"
    REJECTED_INSUFFICIENT_CRITERIA = "rejected_insufficient_criteria"


class ResearchContextPacketV1(FrozenModel):
    """Immutable context packet providing historical research memory to an agent."""

    schema_version: Literal["1"] = RESEARCH_AGENT_SCHEMA_VERSION
    agent_role: ResearchAgentRole
    total_trial_count: int
    median_sharpe_ratio: Decimal | None = None
    max_sharpe_ratio: Decimal | None = None
    active_hypotheses_count: int
    falsified_hypotheses_count: int
    falsified_hypothesis_summaries: tuple[str, ...] = ()
    forbidden_variations: tuple[str, ...] = ()
    available_strategy_types: tuple[str, ...] = ()
    created_at: UTCDateTime
    context_hash: SHA256Hash

    @model_validator(mode="after")
    def validate_packet_integrity(self) -> Self:
        if self.total_trial_count < 0:
            raise ValueError("total_trial_count cannot be negative")
        if self.active_hypotheses_count < 0:
            raise ValueError("active_hypotheses_count cannot be negative")
        if self.falsified_hypotheses_count < 0:
            raise ValueError("falsified_hypotheses_count cannot be negative")
        return self


class HypothesisProposalV1(FrozenModel):
    """Formal hypothesis proposal generated by an AI research agent."""

    schema_version: Literal["1"] = RESEARCH_AGENT_SCHEMA_VERSION
    proposal_id: UUID7
    title: NonBlankStr
    economic_rationale: NonBlankStr
    target_strategy_type: NonBlankStr
    parent_hypothesis_id: UUID7 | None = None
    min_annualized_sharpe: Decimal
    max_drawdown_limit: Decimal
    max_turnover_limit: Decimal
    min_information_coefficient: Decimal | None = None
    created_at: UTCDateTime
    proposal_hash: SHA256Hash

    @model_validator(mode="after")
    def validate_falsification_criteria(self) -> Self:
        if self.min_annualized_sharpe <= Decimal("0"):
            raise ValueError("min_annualized_sharpe must be strictly positive")
        if self.max_drawdown_limit <= Decimal("0") or self.max_drawdown_limit > Decimal(
            "1.0"
        ):
            raise ValueError("max_drawdown_limit must be strictly between 0 and 1.0")
        if self.max_turnover_limit <= Decimal("0"):
            raise ValueError("max_turnover_limit must be strictly positive")
        if (
            self.min_information_coefficient is not None
            and self.min_information_coefficient <= Decimal("0")
        ):
            raise ValueError("min_information_coefficient must be strictly positive")
        return self


class ExperimentSpecificationProposalV1(FrozenModel):
    """Concrete experiment specification proposed for empirical evaluation."""

    schema_version: Literal["1"] = RESEARCH_AGENT_SCHEMA_VERSION
    experiment_proposal_id: UUID7
    hypothesis_proposal_id: UUID7
    strategy_type: NonBlankStr
    proposed_parameters: ImmutableJSON
    parameters_hash: SHA256Hash
    universe_id: NonBlankStr
    rebalance_frequency: NonBlankStr
    created_at: UTCDateTime
    specification_hash: SHA256Hash

    @model_validator(mode="after")
    def validate_parameters_hash(self) -> Self:
        expected = content_hash(self.proposed_parameters)
        if self.parameters_hash != expected:
            raise ValueError(
                f"parameters_hash mismatch: expected {expected}, "
                f"got {self.parameters_hash}"
            )
        return self


class ProposalValidationResultV1(FrozenModel):
    """Deterministic validation audit report for an agent proposal."""

    schema_version: Literal["1"] = RESEARCH_AGENT_SCHEMA_VERSION
    validation_id: UUID7
    proposal_id: UUID7
    status: ProposalValidationStatus
    is_accepted: bool
    rejection_reasons: tuple[str, ...] = ()
    evaluated_at: UTCDateTime
    validation_hash: SHA256Hash

    @model_validator(mode="after")
    def validate_acceptance_consistency(self) -> Self:
        if self.is_accepted and self.status != ProposalValidationStatus.ACCEPTED:
            raise ValueError("is_accepted=True requires status=ACCEPTED")
        if not self.is_accepted and self.status == ProposalValidationStatus.ACCEPTED:
            raise ValueError("is_accepted=False cannot have status=ACCEPTED")
        if not self.is_accepted and not self.rejection_reasons:
            raise ValueError(
                "rejected proposals must specify at least one rejection reason"
            )
        return self


def compute_context_packet_hash(unsigned: Mapping[str, Any]) -> SHA256Hash:
    """Compute deterministic SHA-256 hash for a ResearchContextPacketV1."""
    d = dict(unsigned)
    d.pop("context_hash", None)
    return content_hash(d)


def compute_hypothesis_proposal_hash(unsigned: Mapping[str, Any]) -> SHA256Hash:
    """Compute deterministic SHA-256 hash for a HypothesisProposalV1."""
    d = dict(unsigned)
    d.pop("proposal_hash", None)
    return content_hash(d)


def compute_experiment_specification_proposal_hash(
    unsigned: Mapping[str, Any],
) -> SHA256Hash:
    """Compute deterministic SHA-256 hash for an ExperimentSpecificationProposalV1."""
    d = dict(unsigned)
    d.pop("specification_hash", None)
    return content_hash(d)


def compute_proposal_validation_hash(unsigned: Mapping[str, Any]) -> SHA256Hash:
    """Compute deterministic SHA-256 hash for a ProposalValidationResultV1."""
    d = dict(unsigned)
    d.pop("validation_hash", None)
    return content_hash(d)


def build_research_context_packet(
    *,
    agent_role: ResearchAgentRole,
    total_trial_count: int,
    active_hypotheses_count: int,
    falsified_hypotheses_count: int,
    created_at: UTCDateTime,
    median_sharpe_ratio: Decimal | None = None,
    max_sharpe_ratio: Decimal | None = None,
    falsified_hypothesis_summaries: tuple[str, ...] = (),
    forbidden_variations: tuple[str, ...] = (),
    available_strategy_types: tuple[str, ...] = (),
) -> ResearchContextPacketV1:
    """Construct an immutable ResearchContextPacketV1 with computed hash."""
    unsigned = {
        "schema_version": RESEARCH_AGENT_SCHEMA_VERSION,
        "agent_role": agent_role,
        "total_trial_count": total_trial_count,
        "median_sharpe_ratio": median_sharpe_ratio,
        "max_sharpe_ratio": max_sharpe_ratio,
        "active_hypotheses_count": active_hypotheses_count,
        "falsified_hypotheses_count": falsified_hypotheses_count,
        "falsified_hypothesis_summaries": falsified_hypothesis_summaries,
        "forbidden_variations": forbidden_variations,
        "available_strategy_types": available_strategy_types,
        "created_at": created_at,
    }
    c_hash = compute_context_packet_hash(unsigned)
    return ResearchContextPacketV1.model_validate(
        {
            **unsigned,
            "context_hash": c_hash,
        }
    )


def build_hypothesis_proposal(
    *,
    proposal_id: UUID,
    title: NonBlankStr,
    economic_rationale: NonBlankStr,
    target_strategy_type: NonBlankStr,
    min_annualized_sharpe: Decimal,
    max_drawdown_limit: Decimal,
    max_turnover_limit: Decimal,
    created_at: UTCDateTime,
    parent_hypothesis_id: UUID | None = None,
    min_information_coefficient: Decimal | None = None,
) -> HypothesisProposalV1:
    """Construct an immutable HypothesisProposalV1 with computed hash."""
    unsigned = {
        "schema_version": RESEARCH_AGENT_SCHEMA_VERSION,
        "proposal_id": proposal_id,
        "title": title,
        "economic_rationale": economic_rationale,
        "target_strategy_type": target_strategy_type,
        "parent_hypothesis_id": parent_hypothesis_id,
        "min_annualized_sharpe": min_annualized_sharpe,
        "max_drawdown_limit": max_drawdown_limit,
        "max_turnover_limit": max_turnover_limit,
        "min_information_coefficient": min_information_coefficient,
        "created_at": created_at,
    }
    p_hash = compute_hypothesis_proposal_hash(unsigned)
    return HypothesisProposalV1.model_validate(
        {
            **unsigned,
            "proposal_hash": p_hash,
        }
    )


def build_experiment_specification_proposal(
    *,
    experiment_proposal_id: UUID,
    hypothesis_proposal_id: UUID,
    strategy_type: NonBlankStr,
    proposed_parameters: Mapping[str, Any],
    universe_id: NonBlankStr,
    rebalance_frequency: NonBlankStr,
    created_at: UTCDateTime,
) -> ExperimentSpecificationProposalV1:
    """Construct an immutable ExperimentSpecificationProposalV1 with computed hash."""
    frozen_params = _freeze_json(dict(proposed_parameters))
    p_hash = content_hash(frozen_params)
    unsigned = {
        "schema_version": RESEARCH_AGENT_SCHEMA_VERSION,
        "experiment_proposal_id": experiment_proposal_id,
        "hypothesis_proposal_id": hypothesis_proposal_id,
        "strategy_type": strategy_type,
        "proposed_parameters": frozen_params,
        "parameters_hash": p_hash,
        "universe_id": universe_id,
        "rebalance_frequency": rebalance_frequency,
        "created_at": created_at,
    }
    s_hash = compute_experiment_specification_proposal_hash(unsigned)
    return ExperimentSpecificationProposalV1.model_validate(
        {
            **unsigned,
            "specification_hash": s_hash,
        }
    )


def build_proposal_validation_result(
    *,
    validation_id: UUID,
    proposal_id: UUID,
    status: ProposalValidationStatus,
    is_accepted: bool,
    evaluated_at: UTCDateTime,
    rejection_reasons: tuple[str, ...] = (),
) -> ProposalValidationResultV1:
    """Construct an immutable ProposalValidationResultV1 with computed hash."""
    unsigned = {
        "schema_version": RESEARCH_AGENT_SCHEMA_VERSION,
        "validation_id": validation_id,
        "proposal_id": proposal_id,
        "status": status,
        "is_accepted": is_accepted,
        "rejection_reasons": rejection_reasons,
        "evaluated_at": evaluated_at,
    }
    v_hash = compute_proposal_validation_hash(unsigned)
    return ProposalValidationResultV1.model_validate(
        {
            **unsigned,
            "validation_hash": v_hash,
        }
    )
